flags: {}

extra-package-dbs: []

packages:
  - location: .

resolver: lts-9.1

nix:
    packages: [gmp,git]

extra-deps:
  - universum-0.8.0
  - microlens-0.4.8.1
  - github-0.18
  - zip-archive-0.3.1.1
